os:
  - linux
  - osx

sudo: false
env:
  global:
    - MAKE="make -j 2"

language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.3
  - ruby-head

gemfile:
  - gemfiles/no_rails.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

  exclude:
    - gemfile: gemfiles/no_rails.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/no_rails.gemfile
      rvm: 2.4.5
      os: osx
    - gemfile: gemfiles/rails_4.2.gemfile
      rvm: 2.4.5
      os: osx
    - gemfile: gemfiles/rails_4.2.gemfile
      rvm: 2.4.5
      os: linux
