sudo: false

env:
  global:
    - MAKE="make -j 2"

cache:
  - ccache
  - bundler

language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.3.0
  - rbx-2

matrix:
  allow_failures:
    - rvm: 1.8.7
